spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
management:
  endpoints:
    beans:
      enabled: false
    metrics:
      enabled: true
    web:
      exposure:
        include: info, health, metrics, prometheus